Search.appendIndex(
    [
                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin",
            "name": "Admin",
            "summary": "The\u0020admin\u002Dspecific\u0020functionality\u0020of\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020the\u0020class\u0020and\u0020set\u0020its\u0020properties.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#method___construct"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003Adefine_hooks\u0028\u0029",
            "name": "define_hooks",
            "summary": "Register\u0020all\u0020of\u0020the\u0020hooks\u0020related\u0020to\u0020the\u0020admin\u0020area\u0020functionality\u0020of\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#method_define_hooks"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003Aenqueue_styles\u0028\u0029",
            "name": "enqueue_styles",
            "summary": "Register\u0020the\u0020stylesheets\u0020for\u0020the\u0020admin\u0020area.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#method_enqueue_styles"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003Aenqueue_scripts\u0028\u0029",
            "name": "enqueue_scripts",
            "summary": "Register\u0020the\u0020JavaScript\u0020for\u0020the\u0020admin\u0020area.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#method_enqueue_scripts"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003Aenqueue_script_admin_screen\u0028\u0029",
            "name": "enqueue_script_admin_screen",
            "summary": "Enqueue\u0020JS\u0020for\u0020the\u0020plugin\u0020admin\u0020screen.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#method_enqueue_script_admin_screen"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003Aenqueue_script_table_rates\u0028\u0029",
            "name": "enqueue_script_table_rates",
            "summary": "Enqueue\u0020JS\u0020for\u0020modifying\u0020WooCommerce\u0020table\u002Drates\u0020admin\u0020pages.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#method_enqueue_script_table_rates"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003Adisplay_admin_page\u0028\u0029",
            "name": "display_admin_page",
            "summary": "Create\u0020an\u0020admin\u0020page.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#method_display_admin_page"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003Ashow_admin_parent_page\u0028\u0029",
            "name": "show_admin_parent_page",
            "summary": "Fallback\u0020page,\u0020in\u0020case\u0020there\u0020wasn\u0027t\u0020already\u0020one\u0020there.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#method_show_admin_parent_page"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003Ashow_admin_page\u0028\u0029",
            "name": "show_admin_page",
            "summary": "Markup\u0020for\u0020the\u0020admin\u0020page.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#method_show_admin_page"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003Aadd_acf_link_to_admin\u0028\u0029",
            "name": "add_acf_link_to_admin",
            "summary": "Append\u0020a\u0020link\u0020to\u0020the\u0020list\u0020of\u0020admin\u0020page\u0020links.",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#method_add_acf_link_to_admin"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003A\u0024plugin_slug",
            "name": "plugin_slug",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#property_plugin_slug"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#property_version"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003A\u0024admin_page_links",
            "name": "admin_page_links",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#property_admin_page_links"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003A\u0024util",
            "name": "util",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#property_util"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin\\Admin\u003A\u003A\u0024acf",
            "name": "acf",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Admin-Admin.html#property_acf"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ACFHandler",
            "name": "ACFHandler",
            "summary": "Creates\u0020ACF\u0020fields\u0020and\u0020supplies\u0020getters\u0020for\u0020their\u0020values.",
            "url": "classes/Kerrys-Nationwide-Common-ACFHandler.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ACFHandler\u003A\u003Aadd_options_pages\u0028\u0029",
            "name": "add_options_pages",
            "summary": "Initialise\u0020options\u0020pages.\u0020Each\u0020set\u0020of\u0020ACFs\u0020you\u0020make\u0020will\u0020need\u0020one\u0020of\u0020these.",
            "url": "classes/Kerrys-Nationwide-Common-ACFHandler.html#method_add_options_pages"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ACFHandler\u003A\u003Aadd_options_page\u0028\u0029",
            "name": "add_options_page",
            "summary": "Add\u0020an\u0020ACF\u0020options\u0020page.",
            "url": "classes/Kerrys-Nationwide-Common-ACFHandler.html#method_add_options_page"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ACFHandler\u003A\u003Aadd_fields\u0028\u0029",
            "name": "add_fields",
            "summary": "Add\u0020ACF\u0020field\u0020groups\u0020and\u0020fields\u0020to\u0020an\u0020ACF\u0020options\u0020page.",
            "url": "classes/Kerrys-Nationwide-Common-ACFHandler.html#method_add_fields"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ACFHandler\u003A\u003Aget_min_price_field\u0028\u0029",
            "name": "get_min_price_field",
            "summary": "Return\u0020the\u0020value\u0020of\u0020an\u0020ACF\u0020based\u0020on\u0020the\u0020shorthand\u0020name\u0020\u0028\u0024key\u0029.",
            "url": "classes/Kerrys-Nationwide-Common-ACFHandler.html#method_get_min_price_field"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ACFHandler\u003A\u003Aget_error_message\u0028\u0029",
            "name": "get_error_message",
            "summary": "Error\u0020and\u0020warning\u0020messages.",
            "url": "classes/Kerrys-Nationwide-Common-ACFHandler.html#method_get_error_message"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ACFHandler\u003A\u003Aget_shipping_method_label\u0028\u0029",
            "name": "get_shipping_method_label",
            "summary": "Get\u0020the\u0020shipping\u0020method\u0020label,\u0020defined\u0020in\u0020the\u0020ACF\u0020field,\u0020for\u0020display\u0020on\u0020the\u0020front\u0020end.",
            "url": "classes/Kerrys-Nationwide-Common-ACFHandler.html#method_get_shipping_method_label"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\ActionInterface",
            "name": "ActionInterface",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-ActionInterface.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\ActionInterface\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-ActionInterface.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingCostFromTableRateID",
            "name": "GetShippingCostFromTableRateID",
            "summary": "Get\u0020the\u0020shipping\u0020rate\u0020cost\u0020based\u0020on\u0020the\u0020shipping\u0020rate\u0020ID.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingCostFromTableRateID.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingCostFromTableRateID\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingCostFromTableRateID.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingCostFromWCShippingRate",
            "name": "GetShippingCostFromWCShippingRate",
            "summary": "Get\u0020the\u0020label\u0020from\u0020a\u0020WC_Shipping_Rate\u0020object.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingCostFromWCShippingRate.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingCostFromWCShippingRate\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Get\u0020the\u0020label\u0020from\u0020a\u0020WC_Shipping_Rate\u0020object.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingCostFromWCShippingRate.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingDateBusinessBox",
            "name": "GetShippingDateBusinessBox",
            "summary": "Get\u0020the\u0020delivery\u0020date\u0020of\u0020an\u0020order.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingDateBusinessBox.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingDateBusinessBox\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingDateBusinessBox.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingDateFromOrder",
            "name": "GetShippingDateFromOrder",
            "summary": "Get\u0020the\u0020delivery\u0020date\u0020of\u0020an\u0020order.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingDateFromOrder.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingDateFromOrder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingDateFromOrder.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingDateFromTableRateID",
            "name": "GetShippingDateFromTableRateID",
            "summary": "Get\u0020delivery\u0020date\u0020from\u0020a\u0020table\u002Drate\u0020ID.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingDateFromTableRateID.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingDateFromTableRateID\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Get\u0020delivery\u0020date\u0020from\u0020a\u0020table\u002Drate\u0020ID.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingDateFromTableRateID.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingLabelFromOrder",
            "name": "GetShippingLabelFromOrder",
            "summary": "Get\u0020shipping\u0020label\u0020from\u0020WC_Order\u0020object\u0020or\u0020order\u0020ID.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingLabelFromOrder.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingLabelFromOrder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Get\u0020shipping\u0020label\u0020from\u0020WC_Order\u0020object\u0020or\u0020order\u0020ID.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingLabelFromOrder.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingLabelFromTableRateID",
            "name": "GetShippingLabelFromTableRateID",
            "summary": "Get\u0020shipping\u0020label\u0020from\u0020a\u0020table\u002Drate\u0020ID.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingLabelFromTableRateID.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingLabelFromTableRateID\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Get\u0020shipping\u0020label\u0020from\u0020a\u0020table\u002Drate\u0020ID.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingLabelFromTableRateID.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingLabelFromWCShippingRate",
            "name": "GetShippingLabelFromWCShippingRate",
            "summary": "Get\u0020the\u0020label\u0020from\u0020a\u0020WC_Shipping_Rate\u0020object.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingLabelFromWCShippingRate.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions\\GetShippingLabelFromWCShippingRate\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Get\u0020the\u0020label\u0020from\u0020a\u0020WC_Shipping_Rate\u0020object.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Actions-GetShippingLabelFromWCShippingRate.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\ConditionActionFactory",
            "name": "ConditionActionFactory",
            "summary": "Instantiate\u0020and\u0020populate\u0020a\u0020condition\/action\u0020set\u0020object\u0020based\u0020on\u0020a\u0020supplied\u0020type\u0020parameter.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-ConditionActionFactory.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\ConditionActionFactory\u003A\u003Amake\u0028\u0029",
            "name": "make",
            "summary": "Make\u0020a\u0020set\u0020of\u0020conditions\/actions\u0020that\u0020will\u0020work\u0020all\u0020requests\u0020for\u0020data.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-ConditionActionFactory.html#method_make"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\ConditionActionHandler",
            "name": "ConditionActionHandler",
            "summary": "Object\u002Doriented\u0020implementation\u0020of\u0020an\u0020if\u002Dthen\u002Ddo\u0020statement.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-ConditionActionHandler.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\ConditionActionHandler\u003A\u003Aiterate\u0028\u0029",
            "name": "iterate",
            "summary": "Iterate\u0020of\u0020condition\/action\u0020set\u0020and\u0020run\u0020each.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-ConditionActionHandler.html#method_iterate"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\ConditionActionSet",
            "name": "ConditionActionSet",
            "summary": "A\u0020container\u0020for\u0020condition\u0020and\u0020action\u0020paired\u0020objects.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-ConditionActionSet.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\ConditionActionSet\u003A\u003Aadd_pair\u0028\u0029",
            "name": "add_pair",
            "summary": "Add\u0020a\u0020condition\/action\u0020pair\u0020to\u0020the\u0020list.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-ConditionActionSet.html#method_add_pair"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\ConditionActionSet\u003A\u003Aget_pairs\u0028\u0029",
            "name": "get_pairs",
            "summary": "Get\u0020the\u0020array\u0020of\u0020condition\/action\u0020pairs.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-ConditionActionSet.html#method_get_pairs"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\ConditionActionSet\u003A\u003A\u0024pairs",
            "name": "pairs",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-ConditionActionSet.html#property_pairs"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Conditions\\ConditionInterface",
            "name": "ConditionInterface",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Conditions-ConditionInterface.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Conditions\\ConditionInterface\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Conditions-ConditionInterface.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Conditions\\IfOrder",
            "name": "IfOrder",
            "summary": "Check\u0020that\u0020we\u0020have\u0020a\u0020WC_Order\u0020object\u0020or\u0020ID.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Conditions-IfOrder.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Conditions\\IfOrder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Conditions-IfOrder.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Conditions\\IfTableRateID",
            "name": "IfTableRateID",
            "summary": "Return\u0020true\u0020if\u0020we\u0020have\u0020a\u0020table\u002Drate\u0020ID.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Conditions-IfTableRateID.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Conditions\\IfTableRateID\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Conditions-IfTableRateID.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Conditions\\IfWCShippingRate",
            "name": "IfWCShippingRate",
            "summary": "Check\u0020if\u0020we\u0020have\u0020a\u0020WC_Shipping_Rate\u0020instance.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Conditions-IfWCShippingRate.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Conditions\\IfWCShippingRate\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Return\u0020true\u0020if\u0020\u0024args\u0020is\u0020a\u0020WC_Shipping_Rate\u0020instance.",
            "url": "classes/Kerrys-Nationwide-Common-ConditionActionHandler-Conditions-IfWCShippingRate.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\CollectInStore",
            "name": "CollectInStore",
            "summary": "Shipping\u0020charges\u0020for\u0020local\u0020collection\u0020in\u002Dstore.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-CollectInStore.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\CollectInStore\u003A\u003Aget_delivery_date\u0028\u0029",
            "name": "get_delivery_date",
            "summary": "Return\u0020date\u0020from\u0020which\u0020goods\u0020will\u0020be\u0020ready\u0020to\u0020pick\u0020up.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-CollectInStore.html#method_get_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\DeliveryFactory",
            "name": "DeliveryFactory",
            "summary": "Factory\u0020class\u0020for\u0020delivery\u0020types.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-DeliveryFactory.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\DeliveryFactory\u003A\u003Aconstruct_delivery\u0028\u0029",
            "name": "construct_delivery",
            "summary": "Create\u0020a\u0020delivery\u0020method\u0020object\u0020based\u0020on\u0020the\u0020method\u0020rate\u0020ID.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-DeliveryFactory.html#method_construct_delivery"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\DeliveryInterface",
            "name": "DeliveryInterface",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-DeliveryInterface.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\DeliveryInterface\u003A\u003Aget_delivery_date\u0028\u0029",
            "name": "get_delivery_date",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-DeliveryInterface.html#method_get_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\ExpressDeliveryCalculation",
            "name": "ExpressDeliveryCalculation",
            "summary": "Calculate\u0020the\u0020delivery\u0020day\u0020based\u0020on\u0020params\u0020passed\u0020by\u0020specific\u0020delivery\u0020type.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-ExpressDeliveryCalculation.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\ExpressDeliveryCalculation\u003A\u003Aget_delivery_date\u0028\u0029",
            "name": "get_delivery_date",
            "summary": "Return\u0020the\u0020maximum\u0020express\u0020delivery\u0020time\u0020\u0028days\u0029\u0020based\u0020on\u0020all\u0020items\u0020in\u0020the\u0020cart.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-ExpressDeliveryCalculation.html#method_get_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\ExpressDeliveryCalculation\u003A\u003Aapply_cart_contents\u0028\u0029",
            "name": "apply_cart_contents",
            "summary": "Add\u0020days\u0020based\u0020on\u0020cart\u0020contents.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-ExpressDeliveryCalculation.html#method_apply_cart_contents"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\ExpressDeliveryCalculation\u003A\u003Aapply_non_delivery_days\u0028\u0029",
            "name": "apply_non_delivery_days",
            "summary": "Add\u0020additional\u0020days\u0020until\u0020we\u0020find\u0020a\u0020day\u0020that\u0020isn\u0027t\u0020a\u0020non\u002Ddelivery\nday\u0020\u0028i.e.\u0020a\u0020\u0027delivery\u0020day\u0027,\u0020or\u0020indeed,\u0020a\u0020\u0027non\u002Dnon\u002Ddelivery\u0027\u0020day\u0029",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-ExpressDeliveryCalculation.html#method_apply_non_delivery_days"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\ExpressDeliveryCalculation\u003A\u003Aapply_cutoff_time\u0028\u0029",
            "name": "apply_cutoff_time",
            "summary": "Add\u0020a\u0020day\u0020if\u0020the\u0020user\u0020has\u0020missed\u0020the\u0020cutoff\u0020time.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-ExpressDeliveryCalculation.html#method_apply_cutoff_time"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\ExpressDeliveryCalculation\u003A\u003Adate_after_n_days\u0028\u0029",
            "name": "date_after_n_days",
            "summary": "Get\u0020day\u0020of\u0020the\u0020week\u0020after\u0020a\u0020given\u0020number\u0020of\u0020days\u0020relative\u0020to\u0020current\u0020day.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-ExpressDeliveryCalculation.html#method_date_after_n_days"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\ExpressDeliveryLocal",
            "name": "ExpressDeliveryLocal",
            "summary": "Express\u0020delivery\u0020date\u0020calculation.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-ExpressDeliveryLocal.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\ExpressDeliveryLocal\u003A\u003Aget_delivery_date\u0028\u0029",
            "name": "get_delivery_date",
            "summary": "Initialises\u0020the\u0020delivery\u0020calculation\u0020for\u0020local\u0020express\u0020delivery.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-ExpressDeliveryLocal.html#method_get_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\ExpressDeliveryNationwide",
            "name": "ExpressDeliveryNationwide",
            "summary": "Calculate\u0020delivery\u0020date\u0020for\u0020nationwide\u0020express.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-ExpressDeliveryNationwide.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\ExpressDeliveryNationwide\u003A\u003Aget_delivery_date\u0028\u0029",
            "name": "get_delivery_date",
            "summary": "Initialises\u0020the\u0020delivery\u0020calculation\u0020for\u0020nationwide\u0020express\u0020delivery.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-ExpressDeliveryNationwide.html#method_get_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\StandardDeliveryCalculation",
            "name": "StandardDeliveryCalculation",
            "summary": "Calculate\u0020delivery\u0020day\u0020for\u0020standard\u0020delivery\u0020methods\u0020\u0028local\u0020\u0026\u0020nationwide\u0029",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-StandardDeliveryCalculation.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\StandardDeliveryCalculation\u003A\u003Aget_delivery_date\u0028\u0029",
            "name": "get_delivery_date",
            "summary": "Return\u0020formatted\u0020delivery\u0020day\u0020based\u0020on\u0020rules\u0020passed\u0020as\u0020args.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-StandardDeliveryCalculation.html#method_get_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\StandardDeliveryCalculation\u003A\u003Ais_before_cutoff\u0028\u0029",
            "name": "is_before_cutoff",
            "summary": "Return\u0020true\u0020if\u0020we\u0020are\u0020currently\u0020before\u0020the\u0020cutoff\u0020day\/time.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-StandardDeliveryCalculation.html#method_is_before_cutoff"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\StandardDeliveryCalculation\u003A\u003Ais_this_day\u0028\u0029",
            "name": "is_this_day",
            "summary": "Return\u0020true\u0020if\u0020we\u0020are\u0020currently\u0020on\u0020a\u0020Sunday.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-StandardDeliveryCalculation.html#method_is_this_day"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\StandardDeliveryLocal",
            "name": "StandardDeliveryLocal",
            "summary": "Standard\u0020delivery\u0020date\u0020calculation",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-StandardDeliveryLocal.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\StandardDeliveryLocal\u003A\u003Aget_delivery_date\u0028\u0029",
            "name": "get_delivery_date",
            "summary": "Return\u0020the\u0020delivery\u0020date.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-StandardDeliveryLocal.html#method_get_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\StandardDeliveryNationwide",
            "name": "StandardDeliveryNationwide",
            "summary": "Return\u0020a\u0020standard\u0020nationwide\u0020delivery\u0020date.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-StandardDeliveryNationwide.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates\\StandardDeliveryNationwide\u003A\u003Aget_delivery_date\u0028\u0029",
            "name": "get_delivery_date",
            "summary": "Return\u0020the\u0020delivery\u0020date.",
            "url": "classes/Kerrys-Nationwide-Common-DeliveryDates-StandardDeliveryNationwide.html#method_get_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Shortcodes",
            "name": "Shortcodes",
            "summary": "Provide\u0020shortcodes\u0020for\u0020the\u0020front\u002Dend.",
            "url": "classes/Kerrys-Nationwide-Common-Shortcodes.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Shortcodes\u003A\u003Aadd_shortcodes\u0028\u0029",
            "name": "add_shortcodes",
            "summary": "Add\u0020shortcodes\u0020for\u0020frontend.",
            "url": "classes/Kerrys-Nationwide-Common-Shortcodes.html#method_add_shortcodes"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Shortcodes\u003A\u003Apostcode_lookup\u0028\u0029",
            "name": "postcode_lookup",
            "summary": "Include\u0020markup\u0020for\u0020the\u0020postcode\u0020lookup.",
            "url": "classes/Kerrys-Nationwide-Common-Shortcodes.html#method_postcode_lookup"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Shortcodes\u003A\u003Arender_postcode_lookup\u0028\u0029",
            "name": "render_postcode_lookup",
            "summary": "Render\u0020postcode\u0020lookup\u0020form.",
            "url": "classes/Kerrys-Nationwide-Common-Shortcodes.html#method_render_postcode_lookup"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util",
            "name": "Util",
            "summary": "Utility\u0020methods\u0020for\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method___construct"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003A\u0024_instance",
            "name": "_instance",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#property__instance"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aset_template_var\u0028\u0029",
            "name": "set_template_var",
            "summary": "Set\u0020a\u0020value\u0020the\u0020local\u0020store\u0020for\u0020use\u0020by\u0020a\u0020template.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_set_template_var"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_template_var\u0028\u0029",
            "name": "get_template_var",
            "summary": "Return\u0020a\u0020stored\u0020value.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_template_var"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_timezone\u0028\u0029",
            "name": "get_timezone",
            "summary": "Return\u0020timezone\u0020to\u0020be\u0020used\u0020throughout\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_timezone"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_shipping_method_cost\u0028\u0029",
            "name": "get_shipping_method_cost",
            "summary": "Get\u0020the\u0020shipping\u0020method\u0020cost\u0020for\u0020any\u0020type\u0020of\u0020identifier.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_shipping_method_cost"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_shipping_method_label\u0028\u0029",
            "name": "get_shipping_method_label",
            "summary": "Get\u0020the\u0020shipping\u0020method\u0020label\u0020for\u0020any\u0020type\u0020of\u0020identifier.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_shipping_method_label"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_delivery_date\u0028\u0029",
            "name": "get_delivery_date",
            "summary": "Public\u0020getter\u0020method\u0020for\u0020delivery\u0020date.\u0020Does\u0020some\u0020juggling\u0020to\nensure\u0020it\u0020works\u0020for\u0020session\u0020and\u0020existing\u0020orders\u0020\u0028i.e.\u0020on\u002Dpage\/email\u0029.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_shipping_method_pretty_label\u0028\u0029",
            "name": "get_shipping_method_pretty_label",
            "summary": "Return\u0020the\u0020long\u002Dform\u0020name\u0020and\u0020cost\u0020of\u0020a\u0020shipping\u0020method,\u0020shown\u0020on\u0020front\u002Dend.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_shipping_method_pretty_label"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aformat_delivery_date\u0028\u0029",
            "name": "format_delivery_date",
            "summary": "Format\u0020the\u0020delivery\u0020date,\u0020shown\u0020on\u0020checkout\u0020and\u0020emails.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_format_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aformat_delivery_day\u0028\u0029",
            "name": "format_delivery_day",
            "summary": "Format\u0020the\u0020delivery\u0020date,\u0020shown\u0020on\u0020checkout\u0020and\u0020emails.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_format_delivery_day"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aformat_postcode\u0028\u0029",
            "name": "format_postcode",
            "summary": "Pretty\u0020version\u0020of\u0020postcode\u0020with\u0020a\u0020space\u0020before\u0020the\u0020final\u00203\u0020chars.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_format_postcode"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Acheckout_modify_order\u0028\u0029",
            "name": "checkout_modify_order",
            "summary": "Modify\u0020order\u0020as\u0020it\u0020is\u0020created.\u0020Add\u0020delivery\u0020date,\u0020etc.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_checkout_modify_order"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Ais_business_box\u0028\u0029",
            "name": "is_business_box",
            "summary": "Return\u0020true\u0020if\u0020the\u0020order\u0020contains\u0020an\u0020item\u0020with\u0020the\u0020\u0022box\u0022\u0020shipping\u0020class\u0020\u0028i.e.\u0020it\u0020is\u0020a\u0020business\u0020box\u0029",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_is_business_box"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Arenewal_modify_order\u0028\u0029",
            "name": "renewal_modify_order",
            "summary": "Update\u0020delivery\u0020date\u0020on\u0020order\u0020renewal.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_renewal_modify_order"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_regular_delivery_date_from_order\u0028\u0029",
            "name": "get_regular_delivery_date_from_order",
            "summary": "Get\u0020delivery\u0020date\u0020of\u0020regular\u0020products\u0020\u0028not\u0020business\u0020box\u0029\u0020from\u0020order\u0020object.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_regular_delivery_date_from_order"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_business_box_delivery_date_from_order\u0028\u0029",
            "name": "get_business_box_delivery_date_from_order",
            "summary": "Get\u0020delivery\u0020date\u0020for\u0020a\u0020business\u0020box\u0020from\u0020the\u0020order\u0020object.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_business_box_delivery_date_from_order"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aenforce_business_box_cutoff_time\u0028\u0029",
            "name": "enforce_business_box_cutoff_time",
            "summary": "If\u0020the\u0020cutoff\u0020time\u0020is\u0020past,\u0020move\u0020to\u0020next\u0020available\u0020day.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_enforce_business_box_cutoff_time"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_business_box_delivery_date\u0028\u0029",
            "name": "get_business_box_delivery_date",
            "summary": "Get\u0020delivery\u0020date\u0020for\u0020business\u0020boxes\u0020\u0028chosen\u0020by\u0020customer\u0029",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_business_box_delivery_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_condition_action_result\u0028\u0029",
            "name": "get_condition_action_result",
            "summary": "Helper\u0020function\u0020to\u0020get\u0020value\u0020from\u0020condition\/action\u0020evaluator.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_condition_action_result"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Acart_contains_ambient\u0028\u0029",
            "name": "cart_contains_ambient",
            "summary": "Return\u0020true\u0020if\u0020ambient\u0020product\u0020exists\u0020in\u0020cart.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_cart_contains_ambient"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Acart_contains_subscription\u0028\u0029",
            "name": "cart_contains_subscription",
            "summary": "Returns\u0020true\u0020of\u0020cart\u0020contains\u0020a\u0020subscription.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_cart_contains_subscription"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Acart_contains_wholesale\u0028\u0029",
            "name": "cart_contains_wholesale",
            "summary": "Return\u0020true\u0020if\u0020wholesale\u0020product\u0020exists\u0020in\u0020cart",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_cart_contains_wholesale"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_table_rate_class_id\u0028\u0029",
            "name": "get_table_rate_class_id",
            "summary": "Return\u0020the\u0020rate\u0020ID\u0020from\u0020the\u0020slug.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_table_rate_class_id"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aset_cookie\u0028\u0029",
            "name": "set_cookie",
            "summary": "Set\u0020a\u0020cookie.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_set_cookie"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_cookie\u0028\u0029",
            "name": "get_cookie",
            "summary": "Get\u0020a\u0020cookie\u0020by\u0020name.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_cookie"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_shipping_zone_from_label\u0028\u0029",
            "name": "get_shipping_zone_from_label",
            "summary": "Return\u0020the\u0020shipping\u0020zone\u0020associated\u0020with\u0020the\u0020given\u0020shipping\u0020method\u0020label.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_shipping_zone_from_label"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_delivery_day_from_shipping_zone\u0028\u0029",
            "name": "get_delivery_day_from_shipping_zone",
            "summary": "Given\u0020a\u0020shipping\u0020package,\u0020return\u0020the\u0020delivery\u0020day.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_delivery_day_from_shipping_zone"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_delivery_zone_from_shipping_zone\u0028\u0029",
            "name": "get_delivery_zone_from_shipping_zone",
            "summary": "Given\u0020a\u0020shipping\u0020package,\u0020return\u0020the\u0020delivery\u0020zone.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_delivery_zone_from_shipping_zone"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_delivery_zone_info\u0028\u0029",
            "name": "get_delivery_zone_info",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_delivery_zone_info"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_shipping_zone_name\u0028\u0029",
            "name": "get_shipping_zone_name",
            "summary": "Get\u0020the\u0020WC_Shipping_Zone\u0020object\u0020from\u0020WooCommerce\u0020shipping\u0020packages.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_shipping_zone_name"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Ais_nationwide\u0028\u0029",
            "name": "is_nationwide",
            "summary": "Returns\u0020true\u0020if\u0020the\u0020current\u0020delivery\u0020zone\u0020is\u0020nationwide",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_is_nationwide"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_all_delivery_days_from_postcode\u0028\u0029",
            "name": "get_all_delivery_days_from_postcode",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_all_delivery_days_from_postcode"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_zone_from_postcode\u0028\u0029",
            "name": "get_zone_from_postcode",
            "summary": "Given\u0020a\u0020postcode,\u0020return\u0020the\u0020shipping\u0020zone\u0020\u0028local\/nationwide\u0029.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_zone_from_postcode"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003Aget_shipping_zone_and_day_from_postcode\u0028\u0029",
            "name": "get_shipping_zone_and_day_from_postcode",
            "summary": "Get\u0020the\u0020delivery\u0020days\u0020for\u0020a\u0020particular\u0020postcode.",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#method_get_shipping_zone_and_day_from_postcode"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Util\u003A\u003A\u0024template_vars",
            "name": "template_vars",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-Util.html#property_template_vars"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Validator",
            "name": "Validator",
            "summary": "Validate\u0020cart\u0020contents.",
            "url": "classes/Kerrys-Nationwide-Common-Validator.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Validator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-Validator.html#method___construct"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Validator\u003A\u003Avalidate_cart\u0028\u0029",
            "name": "validate_cart",
            "summary": "Validate\u0020cart\u0020based\u0020on\u0020minimum\u0020value\u0020for\u0020total\u0020and\u0020shipping\u0020class\u0020\u0028from\u0020ACF\u0020fields\u0029.",
            "url": "classes/Kerrys-Nationwide-Common-Validator.html#method_validate_cart"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Validator\u003A\u003Aget_min_subtotal_by_package\u0028\u0029",
            "name": "get_min_subtotal_by_package",
            "summary": "Determine\u0020shipping\u0020zone\u0020and\u0020return\u0020required\u0020min\u0020cart\u0020price.",
            "url": "classes/Kerrys-Nationwide-Common-Validator.html#method_get_min_subtotal_by_package"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Validator\u003A\u003Aget_totals_per_class\u0028\u0029",
            "name": "get_totals_per_class",
            "summary": "Loop\u0020through\u0020cart\u0020and\u0020determine\u0020sub\u002Dtotals\u0020for\u0020each\u0020shipping\u0020class.",
            "url": "classes/Kerrys-Nationwide-Common-Validator.html#method_get_totals_per_class"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Validator\u003A\u003Avalidate_cart_totals\u0028\u0029",
            "name": "validate_cart_totals",
            "summary": "Add\u0020a\u0020notification\u0020if\u0020the\u0020cart\u0020total\u0020is\u0020not\u0020enough.",
            "url": "classes/Kerrys-Nationwide-Common-Validator.html#method_validate_cart_totals"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Validator\u003A\u003Avalidate_class_totals\u0028\u0029",
            "name": "validate_class_totals",
            "summary": "Add\u0020a\u0020notice\u0020if\u0020a\u0020particular\u0020shipping\u0020class\u0020does\u0020not\u0020satisfy\u0020the\u0020minimum\u0020spend.",
            "url": "classes/Kerrys-Nationwide-Common-Validator.html#method_validate_class_totals"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\Validator\u003A\u003A\u0024ui",
            "name": "ui",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Common-Validator.html#property_ui"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Activator",
            "name": "Activator",
            "summary": "Fired\u0020during\u0020plugin\u0020activation.",
            "url": "classes/Kerrys-Nationwide-Core-Activator.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Activator\u003A\u003Aactivate\u0028\u0029",
            "name": "activate",
            "summary": "Short\u0020Description.\u0020\u0028use\u0020period\u0029",
            "url": "classes/Kerrys-Nationwide-Core-Activator.html#method_activate"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Deactivator",
            "name": "Deactivator",
            "summary": "Fired\u0020during\u0020plugin\u0020deactivation.",
            "url": "classes/Kerrys-Nationwide-Core-Deactivator.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Deactivator\u003A\u003Adeactivate\u0028\u0029",
            "name": "deactivate",
            "summary": "Short\u0020Description.\u0020\u0028use\u0020period\u0029",
            "url": "classes/Kerrys-Nationwide-Core-Deactivator.html#method_deactivate"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\HookLoader",
            "name": "HookLoader",
            "summary": "Register\u0020all\u0020actions\u0020and\u0020filters\u0020for\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Core-HookLoader.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\HookLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020the\u0020collections\u0020used\u0020to\u0020maintain\u0020the\u0020actions\u0020and\u0020filters.",
            "url": "classes/Kerrys-Nationwide-Core-HookLoader.html#method___construct"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\HookLoader\u003A\u003Aadd_action\u0028\u0029",
            "name": "add_action",
            "summary": "Add\u0020a\u0020new\u0020action\u0020to\u0020the\u0020collection\u0020to\u0020be\u0020registered\u0020with\u0020WordPress.",
            "url": "classes/Kerrys-Nationwide-Core-HookLoader.html#method_add_action"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\HookLoader\u003A\u003Aadd_filter\u0028\u0029",
            "name": "add_filter",
            "summary": "Add\u0020a\u0020new\u0020filter\u0020to\u0020the\u0020collection\u0020to\u0020be\u0020registered\u0020with\u0020WordPress.",
            "url": "classes/Kerrys-Nationwide-Core-HookLoader.html#method_add_filter"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\HookLoader\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "A\u0020utility\u0020function\u0020that\u0020is\u0020used\u0020to\u0020register\u0020the\u0020actions\u0020and\u0020hooks\u0020into\u0020a\u0020single\ncollection.",
            "url": "classes/Kerrys-Nationwide-Core-HookLoader.html#method_add"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\HookLoader\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Register\u0020the\u0020filters\u0020and\u0020actions\u0020with\u0020WordPress.",
            "url": "classes/Kerrys-Nationwide-Core-HookLoader.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\HookLoader\u003A\u003A\u0024actions",
            "name": "actions",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Core-HookLoader.html#property_actions"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\HookLoader\u003A\u003A\u0024filters",
            "name": "filters",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Core-HookLoader.html#property_filters"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\i18n",
            "name": "i18n",
            "summary": "Define\u0020the\u0020internationalization\u0020functionality.",
            "url": "classes/Kerrys-Nationwide-Core-i18n.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\i18n\u003A\u003Aload_plugin_textdomain\u0028\u0029",
            "name": "load_plugin_textdomain",
            "summary": "Load\u0020the\u0020plugin\u0020text\u0020domain\u0020for\u0020translation.",
            "url": "classes/Kerrys-Nationwide-Core-i18n.html#method_load_plugin_textdomain"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin",
            "name": "Plugin",
            "summary": "The\u0020core\u0020plugin\u0020class.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Define\u0020the\u0020core\u0020functionality\u0020of\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method___construct"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Aset_version\u0028\u0029",
            "name": "set_version",
            "summary": "Set\u0020plugin\u0020version.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_set_version"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Aload_dependencies\u0028\u0029",
            "name": "load_dependencies",
            "summary": "Load\u0020the\u0020required\u0020dependencies\u0020for\u0020this\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_load_dependencies"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Aset_locale\u0028\u0029",
            "name": "set_locale",
            "summary": "Define\u0020the\u0020locale\u0020for\u0020this\u0020plugin\u0020for\u0020internationalization.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_set_locale"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Adefine_admin_hooks\u0028\u0029",
            "name": "define_admin_hooks",
            "summary": "Register\u0020all\u0020of\u0020the\u0020hooks\u0020related\u0020to\u0020the\u0020admin\u0020area\u0020functionality\u0020of\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_define_admin_hooks"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Adefine_public_hooks\u0028\u0029",
            "name": "define_public_hooks",
            "summary": "Register\u0020all\u0020of\u0020the\u0020hooks\u0020related\u0020to\u0020the\u0020public\u002Dfacing\u0020functionality\nof\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_define_public_hooks"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020loader\u0020to\u0020execute\u0020all\u0020of\u0020the\u0020hooks\u0020with\u0020WordPress.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_run"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Aget_plugin_slug\u0028\u0029",
            "name": "get_plugin_slug",
            "summary": "The\u0020name\u0020of\u0020the\u0020plugin\u0020used\u0020to\u0020uniquely\u0020identify\u0020it\u0020within\u0020the\u0020context\u0020of\nWordPress\u0020and\u0020to\u0020define\u0020internationalization\u0020functionality.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_get_plugin_slug"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Aget_loader\u0028\u0029",
            "name": "get_loader",
            "summary": "The\u0020reference\u0020to\u0020the\u0020class\u0020that\u0020orchestrates\u0020the\u0020hooks\u0020with\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_get_loader"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Aget_version\u0028\u0029",
            "name": "get_version",
            "summary": "Retrieve\u0020the\u0020version\u0020number\u0020of\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_get_version"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Aget_admin\u0028\u0029",
            "name": "get_admin",
            "summary": "Return\u0020the\u0020admin\u0020object.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_get_admin"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003Aautoload\u0028\u0029",
            "name": "autoload",
            "summary": "Autoload\u0020classes\u0020in\u0020our\u0020namespace.",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#method_autoload"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003A\u0024loader",
            "name": "loader",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#property_loader"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003A\u0024plugin_slug",
            "name": "plugin_slug",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#property_plugin_slug"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#property_version"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003A\u0024util",
            "name": "util",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#property_util"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003A\u0024acf",
            "name": "acf",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#property_acf"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003A\u0024namespace_length",
            "name": "namespace_length",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#property_namespace_length"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003A\u0024admin",
            "name": "admin",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#property_admin"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core\\Plugin\u003A\u003A\u0024frontend",
            "name": "frontend",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Core-Plugin.html#property_frontend"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\Frontend",
            "name": "Frontend",
            "summary": "The\u0020public\u002Dfacing\u0020functionality\u0020of\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Frontend-Frontend.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\Frontend\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020the\u0020class\u0020and\u0020set\u0020its\u0020properties.",
            "url": "classes/Kerrys-Nationwide-Frontend-Frontend.html#method___construct"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\Frontend\u003A\u003Adefine_hooks\u0028\u0029",
            "name": "define_hooks",
            "summary": "Register\u0020all\u0020of\u0020the\u0020hooks\u0020related\u0020to\u0020the\u0020public\u002Dfacing\u0020functionality\u0020of\u0020the\u0020plugin.",
            "url": "classes/Kerrys-Nationwide-Frontend-Frontend.html#method_define_hooks"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\Frontend\u003A\u003Aenqueue_styles\u0028\u0029",
            "name": "enqueue_styles",
            "summary": "Register\u0020the\u0020stylesheets\u0020for\u0020the\u0020public\u002Dfacing\u0020side\u0020of\u0020the\u0020site.",
            "url": "classes/Kerrys-Nationwide-Frontend-Frontend.html#method_enqueue_styles"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\Frontend\u003A\u003Aenqueue_scripts\u0028\u0029",
            "name": "enqueue_scripts",
            "summary": "Register\u0020the\u0020JavaScript\u0020for\u0020the\u0020public\u002Dfacing\u0020side\u0020of\u0020the\u0020site.",
            "url": "classes/Kerrys-Nationwide-Frontend-Frontend.html#method_enqueue_scripts"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\Frontend\u003A\u003A\u0024plugin_slug",
            "name": "plugin_slug",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Frontend-Frontend.html#property_plugin_slug"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\Frontend\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Frontend-Frontend.html#property_version"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\Frontend\u003A\u003A\u0024util",
            "name": "util",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Frontend-Frontend.html#property_util"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\PostcodeLookup",
            "name": "PostcodeLookup",
            "summary": "Logic\u0020for\u0020postcode\u0020lookup\u0020form.",
            "url": "classes/Kerrys-Nationwide-Frontend-PostcodeLookup.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\PostcodeLookup\u003A\u003Aget_form_markup_popup\u0028\u0029",
            "name": "get_form_markup_popup",
            "summary": "Form",
            "url": "classes/Kerrys-Nationwide-Frontend-PostcodeLookup.html#method_get_form_markup_popup"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\PostcodeLookup\u003A\u003Aget_results_markup_popup\u0028\u0029",
            "name": "get_results_markup_popup",
            "summary": "Results",
            "url": "classes/Kerrys-Nationwide-Frontend-PostcodeLookup.html#method_get_results_markup_popup"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\PostcodeLookup\u003A\u003Aget_form_markup_cart\u0028\u0029",
            "name": "get_form_markup_cart",
            "summary": "Show\u0020the\u0020postcode\u0020lookup\u0020form\u0020in\u0020the\u0020cart\u0020sidebar.",
            "url": "classes/Kerrys-Nationwide-Frontend-PostcodeLookup.html#method_get_form_markup_cart"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\PostcodeLookup\u003A\u003Aget_results_markup_cart\u0028\u0029",
            "name": "get_results_markup_cart",
            "summary": "Results\u0020in\u0020the\u0020cart\u0020sidebar",
            "url": "classes/Kerrys-Nationwide-Frontend-PostcodeLookup.html#method_get_results_markup_cart"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\PostcodeLookup\u003A\u003Apostcode_lookup_callback\u0028\u0029",
            "name": "postcode_lookup_callback",
            "summary": "Receive\u0020request\u0020from\u0020javascript.",
            "url": "classes/Kerrys-Nationwide-Frontend-PostcodeLookup.html#method_postcode_lookup_callback"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI",
            "name": "UI",
            "summary": "Responsibility\u0020for\u0020checkout\u002Donly\u0020functionality.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method___construct"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Ainvalid_cart\u0028\u0029",
            "name": "invalid_cart",
            "summary": "Add\u0020a\u0020set\u0020of\u0020notices\u0020to\u0020be\u0020displayed\u0020in\u0020the\u0020front\u0020end\u0020by\u0020WooCommerce.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_invalid_cart"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Acart_updated\u0028\u0029",
            "name": "cart_updated",
            "summary": "Cart\u0020was\u0020updated,\u0020clear\u0020notifications\u0020and\u0020do\u0020any\u0020other\u0020required\u0020actions.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_cart_updated"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Acompile_notices\u0028\u0029",
            "name": "compile_notices",
            "summary": "Compile\u0020strings\u0020with\u0020sprintf.\u0020ACF\u0020fields\u0020that\u0020populate\u0020the\u0020array\u0020should\u0020therefore\ncontain\u0020the\u0020appropriate\u0020markers\u0020\u0025s\/\u0025d\u0020in\u0020the\u0020text\u0020to\u0020be\u0020replaced\u0020here.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_compile_notices"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Adisplay_notices\u0028\u0029",
            "name": "display_notices",
            "summary": "Display\u0020the\u0020notices\u0020with\u0020the\u0020correct\u0020type\u0020\u0028error\/warning\/success\u0029",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_display_notices"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Adisable_proceed_button\u0028\u0029",
            "name": "disable_proceed_button",
            "summary": "Disable\u0020the\u0020\u0022Proceed\u0020to\u0020checkout\u0022\u0020button\u0020on\u0020the\u0020cart\u0020page.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_disable_proceed_button"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Aget_shipping_method_name_cost\u0028\u0029",
            "name": "get_shipping_method_name_cost",
            "summary": "Get\u0020the\u0020custom\u0020name\u0020of\u0020the\u0020shipping\u0020method\u0020added\u0020in\u0020ACF.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_get_shipping_method_name_cost"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Aupdate_shipping_method\u0028\u0029",
            "name": "update_shipping_method",
            "summary": "Control\u0020which\u0020shipping\u0020methods\u0020are\u0020displayed\u0020to\u0020the\u0020user\u0020based\u0020on\u0020cart\u0020contents.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_update_shipping_method"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Ais_collection_delivery_type\u0028\u0029",
            "name": "is_collection_delivery_type",
            "summary": "Return\u0020true\u0020if\u0020the\u0020shipping\u0020method\u0020is\u0020a\u0020\u0022collection\u0022\u0020type.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_is_collection_delivery_type"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Aget_shipping_method_label\u0028\u0029",
            "name": "get_shipping_method_label",
            "summary": "Return\u0020correct\u0020\u0022pretty\u0022\u0020label\u0020for\u0020shipping\u0020method.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_get_shipping_method_label"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Apostcode_lookup_results\u0028\u0029",
            "name": "postcode_lookup_results",
            "summary": "Pass\u0020in\u0020a\u0020postcode,\u0020get\u0020back\u0020an\u0020array\u0020of\u0020delivery\u0020days\u0020for\u0020each\u0020delivery\/product\u0020type.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_postcode_lookup_results"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Aget_zone_from_postcode\u0028\u0029",
            "name": "get_zone_from_postcode",
            "summary": "Get\u0020shipping\u0020zone\u0020from\u0020postcode\nE.g.\u0020Input\u003A\u0020NE1\u00204SX,\u0020Output\u003A\u0020\u0027nationwide\u0027",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_get_zone_from_postcode"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Amaybe_get_zone_without_postcode\u0028\u0029",
            "name": "maybe_get_zone_without_postcode",
            "summary": "Attempt\u0020to\u0020get\u0020zone\u0020from\u0020currently\u0020logged\u002Din\u0020user.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_maybe_get_zone_without_postcode"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Aformat_postcode\u0028\u0029",
            "name": "format_postcode",
            "summary": "Format\u0020a\u0020UK\u0020postcode\u0020with\u0020a\u0020space\u0020before\u0020the\u0020final\u00203\u0020characters.",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_format_postcode"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Aformat_datetime_to_day\u0028\u0029",
            "name": "format_datetime_to_day",
            "summary": "Format\u0020a\u0020date\u0020object\u0020as\u0020a\u0020delivery\u0020day",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_format_datetime_to_day"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003Aformat_datetime_to_date\u0028\u0029",
            "name": "format_datetime_to_date",
            "summary": "Format\u0020a\u0020date\u0020object\u0020as\u0020a\u0020delivery\u0020day",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#method_format_datetime_to_date"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend\\UI\u003A\u003A\u0024util",
            "name": "util",
            "summary": "",
            "url": "classes/Kerrys-Nationwide-Frontend-UI.html#property_util"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\activate_kerrys_nationwide\u0028\u0029",
            "name": "activate_kerrys_nationwide",
            "summary": "The\u0020code\u0020that\u0020runs\u0020during\u0020plugin\u0020activation.",
            "url": "namespaces/kerrys-nationwide.html#function_activate_kerrys_nationwide"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\deactivate_kerrys_nationwide\u0028\u0029",
            "name": "deactivate_kerrys_nationwide",
            "summary": "The\u0020code\u0020that\u0020runs\u0020during\u0020plugin\u0020deactivation.",
            "url": "namespaces/kerrys-nationwide.html#function_deactivate_kerrys_nationwide"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\run_kerrys_nationwide\u0028\u0029",
            "name": "run_kerrys_nationwide",
            "summary": "Begins\u0020execution\u0020of\u0020the\u0020plugin.",
            "url": "namespaces/kerrys-nationwide.html#function_run_kerrys_nationwide"
        },                {
            "fqsen": "\\Autoloader",
            "name": "Autoloader",
            "summary": "Auto\u002Dload\u0020classes\u0020for\u0020the\u0020plugin.",
            "url": "classes/Autoloader.html"
        },                {
            "fqsen": "\\Autoloader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Autoloader\u0020constructor.",
            "url": "classes/Autoloader.html#method___construct"
        },                {
            "fqsen": "\\Autoloader\u003A\u003Aactions\u0028\u0029",
            "name": "actions",
            "summary": "Register\u0020action\u0020hooks.",
            "url": "classes/Autoloader.html#method_actions"
        },                {
            "fqsen": "\\Autoloader\u003A\u003Aload_class_list\u0028\u0029",
            "name": "load_class_list",
            "summary": "Load\u0020the\u0020class\u0020list\u0020if\u0020it\u0020exists",
            "url": "classes/Autoloader.html#method_load_class_list"
        },                {
            "fqsen": "\\Autoloader\u003A\u003A\u0024_instance",
            "name": "_instance",
            "summary": "",
            "url": "classes/Autoloader.html#property__instance"
        },                {
            "fqsen": "\\Autoloader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Class\u0020Loader.",
            "url": "classes/Autoloader.html#method_load"
        },                {
            "fqsen": "\\Autoloader\u003A\u003Awrite_file\u0028\u0029",
            "name": "write_file",
            "summary": "Write\u0020class\u0020file\u0020paths\u0020to\u0020a\u0020file\u0020to\u0020be\u0020used\u0020as\u0020an\u0020include.",
            "url": "classes/Autoloader.html#method_write_file"
        },                {
            "fqsen": "\\Autoloader\u003A\u003A\u0024class_list",
            "name": "class_list",
            "summary": "",
            "url": "classes/Autoloader.html#property_class_list"
        },                {
            "fqsen": "\\Autoloader\u003A\u003A\u0024base_namespace",
            "name": "base_namespace",
            "summary": "",
            "url": "classes/Autoloader.html#property_base_namespace"
        },                {
            "fqsen": "\\Autoloader\u003A\u003A\u0024plugin_path",
            "name": "plugin_path",
            "summary": "",
            "url": "classes/Autoloader.html#property_plugin_path"
        },                {
            "fqsen": "\\Autoloader\u003A\u003A\u0024class_list_file",
            "name": "class_list_file",
            "summary": "",
            "url": "classes/Autoloader.html#property_class_list_file"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Admin",
            "name": "Admin",
            "summary": "",
            "url": "namespaces/kerrys-nationwide-admin.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common",
            "name": "Common",
            "summary": "",
            "url": "namespaces/kerrys-nationwide-common.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Actions",
            "name": "Actions",
            "summary": "",
            "url": "namespaces/kerrys-nationwide-common-conditionactionhandler-actions.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler",
            "name": "ConditionActionHandler",
            "summary": "",
            "url": "namespaces/kerrys-nationwide-common-conditionactionhandler.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\ConditionActionHandler\\Conditions",
            "name": "Conditions",
            "summary": "",
            "url": "namespaces/kerrys-nationwide-common-conditionactionhandler-conditions.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Common\\DeliveryDates",
            "name": "DeliveryDates",
            "summary": "",
            "url": "namespaces/kerrys-nationwide-common-deliverydates.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/kerrys-nationwide-core.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide\\Frontend",
            "name": "Frontend",
            "summary": "",
            "url": "namespaces/kerrys-nationwide-frontend.html"
        },                {
            "fqsen": "\\Kerrys_Nationwide",
            "name": "Kerrys_Nationwide",
            "summary": "",
            "url": "namespaces/kerrys-nationwide.html"
        }            ]
);
